// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'student_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

StudentModel _$StudentModelFromJson(Map<String, dynamic> json) => StudentModel(
      status: json['status'] as bool?,
      message: json['message'] as String?,
      records: (json['records'] as List<dynamic>)
          .map((e) => StudentRecord.fromJson(e as Map<String, dynamic>))
          .toList(),
      commondata: json['commondata'] as String?,
      formStatus: json['formStatus'] as String?,
      sub_type: json['sub_type'] as String?,
      grades: json['grades'] as String?,
      subject_mark: json['subject_mark'] as String?,
    );

Map<String, dynamic> _$StudentModelToJson(StudentModel instance) =>
    <String, dynamic>{
      'status': instance.status,
      'message': instance.message,
      'records': instance.records,
      'commondata': instance.commondata,
      'formStatus': instance.formStatus,
      'sub_type': instance.sub_type,
      'grades': instance.grades,
      'subject_mark': instance.subject_mark,
    };

StudentRecord _$StudentRecordFromJson(Map<String, dynamic> json) =>
    StudentRecord(
      name: json['name'] as String?,
      sT_ID: json['sT_ID'] as String?,
      user_ID: json['user_ID'] as String?,
      sT_PermanentEduNo: json['sT_PermanentEduNo'] as String?,
      branchID: json['branchID'] as String?,
      admnNo: json['admnNo'] as String?,
      classID: json['classID'] as String?,
      className: json['className'] as String?,
      rollNo: json['rollNo'] as String?,
      sT_Name: json['sT_Name'] as String?,
      sT_DOB: json['sT_DOB'] as String?,
      sT_DOA: json['sT_DOA'] as String?,
      sT_Address: json['sT_Address'] as String?,
      guardianName: json['guardianName'] as String?,
      guardianMobile: json['guardianMobile'] as String?,
      guardianEmail: json['guardianEmail'] as String?,
      guardianReletion: json['guardianReletion'] as String?,
      guardianAadharNo: json['guardianAadharNo'] as String?,
      passCode: json['passCode'] as String?,
      blood_Group: json['blood_Group'] as String?,
      sT_Gender: json['sT_Gender'] as String?,
      hobby: json['hobby'] as String?,
      sT_Nationality: json['sT_Nationality'] as String?,
      religion: json['religion'] as String?,
      casteID: json['casteID'] as String?,
      categoryID: json['categoryID'] as String?,
      billBookNo: json['billBookNo'] as String?,
      admittedInClass: json['admittedInClass'] as String?,
      sT_AadharNo: json['sT_AadharNo'] as String?,
      staffWard: json['staffWard'] as String?,
      staffCode: json['staffCode'] as String?,
      is_Boarding: json['is_Boarding'] as String?,
      is_New_Admn: json['is_New_Admn'] as String?,
      is_Transport: json['is_Transport'] as String?,
      is_ICard: json['is_ICard'] as String?,
      previousSchool: json['previousSchool'] as String?,
      previousSchoolAddress: json['previousSchoolAddress'] as String?,
      lastClassAttendedInPreviousSchool:
          json['lastClassAttendedInPreviousSchool'] as String?,
      previousSchoolLeftYear: json['previousSchoolLeftYear'] as String?,
      houseID: json['houseID'] as String?,
      photo: json['photo'] as String?,
      sR_No: json['sR_No'] as String?,
      boardRegNo: json['boardRegNo'] as String?,
      father_Name: json['father_Name'] as String?,
      father_DOB: json['father_DOB'] as String?,
      father_Qualification: json['father_Qualification'] as String?,
      father_Profession: json['father_Profession'] as String?,
      father_Designation: json['father_Designation'] as String?,
      father_ResiAdd: json['father_ResiAdd'] as String?,
      father_OffAdd: json['father_OffAdd'] as String?,
      father_Mobile: json['father_Mobile'] as String?,
      father_Off_Mobile: json['father_Off_Mobile'] as String?,
      father_Email: json['father_Email'] as String?,
      father_AadharNo: json['father_AadharNo'] as String?,
      father_PanNo: json['father_PanNo'] as String?,
      father_Income_Yearly: json['father_Income_Yearly'] as String?,
      father_Photo: json['father_Photo'] as String?,
      mother_Name: json['mother_Name'] as String?,
      mother_DOB: json['mother_DOB'] as String?,
      mother_Qualification: json['mother_Qualification'] as String?,
      mother_Profession: json['mother_Profession'] as String?,
      mother_Designation: json['mother_Designation'] as String?,
      mother_ResiAdd: json['mother_ResiAdd'] as String?,
      mother_OffAdd: json['mother_OffAdd'] as String?,
      mother_Mobile: json['mother_Mobile'] as String?,
      mother_Off_Mobile: json['mother_Off_Mobile'] as String?,
      mother_Email: json['mother_Email'] as String?,
      mother_AadharNo: json['mother_AadharNo'] as String?,
      mother_PanNo: json['mother_PanNo'] as String?,
      mother_Income_Yearly: json['mother_Income_Yearly'] as String?,
      mother_Photo: json['mother_Photo'] as String?,
      dateOfanniversary: json['dateOfanniversary'] as String?,
      enquiryNo: json['enquiryNo'] as String?,
      groupName: json['groupName'] as String?,
      chkStdId: json['chkStdId'] as String?,
      isCheckedOrNot: json['isCheckedOrNot'] as String?,
      attrVal: json['attrVal'] as String?,
      schoolBoard: json['schoolBoard'] as String?,
      stdStrength: json['stdStrength'] as String?,
    );

Map<String, dynamic> _$StudentRecordToJson(StudentRecord instance) =>
    <String, dynamic>{
      'name': instance.name,
      'sT_ID': instance.sT_ID,
      'user_ID': instance.user_ID,
      'sT_PermanentEduNo': instance.sT_PermanentEduNo,
      'branchID': instance.branchID,
      'admnNo': instance.admnNo,
      'classID': instance.classID,
      'className': instance.className,
      'rollNo': instance.rollNo,
      'sT_Name': instance.sT_Name,
      'sT_DOB': instance.sT_DOB,
      'sT_DOA': instance.sT_DOA,
      'sT_Address': instance.sT_Address,
      'guardianName': instance.guardianName,
      'guardianMobile': instance.guardianMobile,
      'guardianEmail': instance.guardianEmail,
      'guardianReletion': instance.guardianReletion,
      'guardianAadharNo': instance.guardianAadharNo,
      'passCode': instance.passCode,
      'blood_Group': instance.blood_Group,
      'sT_Gender': instance.sT_Gender,
      'hobby': instance.hobby,
      'sT_Nationality': instance.sT_Nationality,
      'religion': instance.religion,
      'casteID': instance.casteID,
      'categoryID': instance.categoryID,
      'billBookNo': instance.billBookNo,
      'admittedInClass': instance.admittedInClass,
      'sT_AadharNo': instance.sT_AadharNo,
      'staffWard': instance.staffWard,
      'staffCode': instance.staffCode,
      'is_Boarding': instance.is_Boarding,
      'is_New_Admn': instance.is_New_Admn,
      'is_Transport': instance.is_Transport,
      'is_ICard': instance.is_ICard,
      'previousSchool': instance.previousSchool,
      'previousSchoolAddress': instance.previousSchoolAddress,
      'lastClassAttendedInPreviousSchool':
          instance.lastClassAttendedInPreviousSchool,
      'previousSchoolLeftYear': instance.previousSchoolLeftYear,
      'houseID': instance.houseID,
      'photo': instance.photo,
      'sR_No': instance.sR_No,
      'boardRegNo': instance.boardRegNo,
      'father_Name': instance.father_Name,
      'father_DOB': instance.father_DOB,
      'father_Qualification': instance.father_Qualification,
      'father_Profession': instance.father_Profession,
      'father_Designation': instance.father_Designation,
      'father_ResiAdd': instance.father_ResiAdd,
      'father_OffAdd': instance.father_OffAdd,
      'father_Mobile': instance.father_Mobile,
      'father_Off_Mobile': instance.father_Off_Mobile,
      'father_Email': instance.father_Email,
      'father_AadharNo': instance.father_AadharNo,
      'father_PanNo': instance.father_PanNo,
      'father_Income_Yearly': instance.father_Income_Yearly,
      'father_Photo': instance.father_Photo,
      'mother_Name': instance.mother_Name,
      'mother_DOB': instance.mother_DOB,
      'mother_Qualification': instance.mother_Qualification,
      'mother_Profession': instance.mother_Profession,
      'mother_Designation': instance.mother_Designation,
      'mother_ResiAdd': instance.mother_ResiAdd,
      'mother_OffAdd': instance.mother_OffAdd,
      'mother_Mobile': instance.mother_Mobile,
      'mother_Off_Mobile': instance.mother_Off_Mobile,
      'mother_Email': instance.mother_Email,
      'mother_AadharNo': instance.mother_AadharNo,
      'mother_PanNo': instance.mother_PanNo,
      'mother_Income_Yearly': instance.mother_Income_Yearly,
      'mother_Photo': instance.mother_Photo,
      'dateOfanniversary': instance.dateOfanniversary,
      'enquiryNo': instance.enquiryNo,
      'groupName': instance.groupName,
      'chkStdId': instance.chkStdId,
      'isCheckedOrNot': instance.isCheckedOrNot,
      'attrVal': instance.attrVal,
      'schoolBoard': instance.schoolBoard,
      'stdStrength': instance.stdStrength,
    };
