// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKfkVEsTdz2Dl5lchw5JMpZL_tniZpqWc',
    appId: '1:817242233313:android:26036e32acafa900521aa0',
    messagingSenderId: '817242233313',
    projectId: 'sms-push-notification-ff543',
    databaseURL: 'https://sms-push-notification-ff543-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sms-push-notification-ff543.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIrcWRXH8Jr2dcEJPuq0K1sp7QutHcl88',
    appId: '1:817242233313:ios:057e04fb25c2635a521aa0',
    messagingSenderId: '817242233313',
    projectId: 'sms-push-notification-ff543',
    databaseURL: 'https://sms-push-notification-ff543-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sms-push-notification-ff543.appspot.com',
    iosBundleId: 'com.decora.school',
  );
}
